# Sourced by run-namespace.sh and run-qemu.sh, which define expect(), reject()
# and $ARCH. EXPECT_TASKS is the staged task count.

expect "init $ARCH starting, pid 1"
expect "${EXPECT_TASKS:-12} tasks in /tasks"
expect "ok: started pid"
expect "FIXTURE ok started"
expect "FIXTURE probe ran"
expect "FIXTURE oneshot ran"
expect "oneshot: done"
reject "not a schedule"
expect "flap: exit 3 sig 0, respawn in"
expect "flap: FAILED after"
expect "hangcheck: probe timed out, killing pid"
expect "hangcheck: restarting on probe failure"
expect "hangcheck: FAILED after"
expect "FIXTURE tick fired"
expect "FIXTURE logfile begin"
expect "ok-stderr-line"
expect "flap-dying"
expect "FIXTURE selftest done"
expect "shutdown requested by signal 10"
expect "syncing"
reject "PANIC"
reject "Kernel panic"
